"""fix datetime

Revision ID: 491535bfd4df
Revises: 50ff7a08a83f
Create Date: 2026-04-06 10:41:40.503995

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '491535bfd4df'
down_revision = '50ff7a08a83f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DATETIME(), nullable=True))

    # ### end Alembic commands ###
