"""empty message

Revision ID: 57ea00da1165
Revises: 491535bfd4df
Create Date: 2026-05-28 20:56:35.078298

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57ea00da1165'
down_revision = '491535bfd4df'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file', sa.String(length=300), nullable=True))
        batch_op.add_column(sa.Column('file_type', sa.String(length=50), nullable=True))

    with op.batch_alter_table('profile_like', schema=None) as batch_op:
        batch_op.alter_column('liked_user',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)
        batch_op.alter_column('liked_by',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('support_message', schema=None) as batch_op:
        batch_op.alter_column('sender',
               existing_type=sa.TEXT(),
               type_=sa.String(length=10),
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.String(length=200),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('password',
               existing_type=sa.String(length=200),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('support_message', schema=None) as batch_op:
        batch_op.alter_column('sender',
               existing_type=sa.String(length=10),
               type_=sa.TEXT(),
               existing_nullable=True,
               existing_server_default=sa.text("'user'"))

    with op.batch_alter_table('profile_like', schema=None) as batch_op:
        batch_op.alter_column('liked_by',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
        batch_op.alter_column('liked_user',
               existing_type=sa.String(length=20),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('file_type')
        batch_op.drop_column('file')

    # ### end Alembic commands ###
