"""add cleared_at

Revision ID: 8ef0a416b810
Revises: 57ea00da1165
Create Date: 2026-06-11 21:33:01.542832

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8ef0a416b810'
down_revision = '57ea00da1165'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('file')
        batch_op.drop_column('file_type')

    with op.batch_alter_table('user_action', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cleared_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_action', schema=None) as batch_op:
        batch_op.drop_column('cleared_at')

    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('file_type', sa.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('file', sa.VARCHAR(length=300), nullable=True))

    # ### end Alembic commands ###
